version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'prueba'
      MYSQL_USER: 'prueba'
      MYSQL_PASSWORD: 'pruebapass'
      MYSQL_ROOT_PASSWORD: 'pruebapass'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
